### ISSUE TITLE
crashing weight loss/gain activity

### ISSUE THREAD

**Issue by amitYadavDev** [SaumyaSingh1/Fitofy-India#11]

**Comment by saumya1singh** [comment]
@amit6663  you want to work on this?

**Comment by gouri-panda** [comment]
@SaumyaSingh1  Can i work with this issue?

**Comment by saumya1singh** [comment]
If @amit6663 is not working then you are good to go @gouri-panda

**Comment by saumya1singh** [comment]
@amit6663  should I assign this to @gouri-panda  if you are not working ?

**Comment by amitYadavDev** [comment]
> @amit6663 should I assign this to @gouri-panda if you are not working ?

yes, ma'am @SaumyaSingh1 assign them.

**Comment by gouri-panda** [comment]
@amit6663  You can close this issue now.

**Comment by amitYadavDev** [comment]
okay
