### ISSUE TITLE
GymMainActivity Activity not found.

### ISSUE THREAD

**Issue by gouri-panda** [SaumyaSingh1/Fitofy-India#2]
https://github.com/SaumyaSingh1/Fitofy-India/blob/76ee4cc8e7e1b4208ed93e1b0d2435ba162b1571/app/src/main/java/com/saumya/fitofyindia/IndividualMain.java#L33

**Comment by saumya1singh** [comment]
Hey @gouri-panda  , Thanks for showing interest in the project ! That activity is to be designed by the participants .
