### ISSUE TITLE
Firebase OTP verification failed.

### ISSUE THREAD

**Issue by gouri-panda** [SaumyaSingh1/Fitofy-India#3]
When I entered my phone number and it shows in the VerificationActivity. The message was this app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console

**Comment by saumya1singh** [comment]
> When I entered my phone number and it shows in the VerificationActivity. The message was this app is not authorized to use Firebase Authentication. Please verify that the correct package name and SHA-1 are configured in the Firebase Console

@gouri-panda  make sure that the data or wifi was switched on!
It's working perfectly fine for me .

**Comment by gouri-panda** [comment]
@SaumyaSingh1  I did it on the emulator and both data and wifi were on.

**Comment by saumya1singh** [comment]
@gouri-panda  Emulator can't work for OTP !

**Comment by saumya1singh** [comment]
> @SaumyaSingh1 I did it on the emulator and both data and wifi were on.

Use your android phone it will work fine for you .

**Comment by gouri-panda** [comment]
I did it. It didn't work either Here is the toast message of error.

<img width="250" alt="Screenshot 2019-12-09 at 8 58 59 PM" src="https://user-images.githubusercontent.com/43576162/70516700-73fb9f00-1b5d-11ea-8e29-1d718a00b9b5.png">

**Comment by saumya1singh** [comment]
> I did it. It didn't work either Here is the toast message of error.
> 
> <img alt="Screenshot 2019-12-09 at 8 58 59 PM" width="250" src="https://user-images.githubusercontent.com/43576162/70516700-73fb9f00-1b5d-11ea-8e29-1d718a00b9b5.png">

okay i will check it .
