### ISSUE TITLE
Fix Firebase issue of the application .

### ISSUE THREAD

**Issue by saumya1singh** [SaumyaSingh1/Fitofy-India#7]

**Comment by gouri-panda** [comment]
Hey, @SaumyaSingh1  I would like to work with this issue.

**Comment by saumya1singh** [comment]
Go ahead @gouri-panda

**Comment by gouri-panda** [comment]
@SaumyaSingh1  I think you added phone numbers for testing in firebase authentication.

**Comment by saumya1singh** [comment]
@gouri-panda  letme check it once.

**Comment by saumya1singh** [comment]
@gouri-panda  For now i have disabled firebase !
An issue for "creating login will be created soon".

**Comment by gouri-panda** [comment]
@SaumyaSingh1  You can set app's SHA-1 hash in the Firebase console

**Comment by saumya1singh** [comment]
@gouri-panda  I want the participants to work on it ! I will soon create an issue for it . 
Thankyou for your valuable suggestions 🎉💯
